// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const variantOption: string;
export const size: string;
export const dark: string;
export const active: string;
